### ISSUE TITLE
Missing files in order to run the Paper plots (GutenTAG&Benchmark)

### ISSUE THREAD

**Issue by B-Seif** [HPI-Information-Systems/TimeEval#3] opened 2022-07-10 17:47 UTC
Hi, I want to run this  [Paper plots notebook](https://github.com/HPI-Information-Systems/TimeEval/blob/main/notebooks/Paper%20plots%20(GutenTAG%26Benchmark).ipynb) and I would like to have access to the various files used in it.
Here is the list:
```python
gutentag_data_path  
benchmark_data_path 
gutentag_result_path 
benchmark_result_path 
```
I was able to access only to this  [results file ](https://owncloud.hpi.de/s/i3LLY6J8mCHhcgZ/download) and I don't know if it's gutenTag or benchmark results. 

Thanks

**Comment by CodeLionX** [comment] 2022-07-10 21:42
Hi again,

We have committed the output of the cells, so that GitHub can render the tables and plots. If you just want to see those, you can look at them on GitHub.

If you want to reproduce our results, you would need all our datasets and results. We have not provided the full result directories of our experiments because of their big size (14 GB compressed). We just uploaded the preprocessed DataFrame `df` that contains the combined results (that's the file you already have [⬇️](https://owncloud.hpi.de/s/i3LLY6J8mCHhcgZ/download)), which is referenced with the name `paper-plots-results.csv` in the Notebook. This means that the computations at the beginning of the notebook won't work (they are for the raw result directories).

You should, however, be able to completely skip the preprocessing cells in the notebook and directly start from Python-Cell 12 or the header _Dataset overview (grouped by collection)_. You will still require the data file paths `gutentag_data_path` and `benchmark_data_path`, though.

**For the datasets:**

- Got to https://hpi-information-systems.github.io/timeeval-evaluation-paper/notebooks/Datasets.html#sources and download all dataset collections (the blue arrow)
- Create folder for the "Benchmark" datasets: `mkdir <benchmark_data_path>`
- Extract all dataset collections **except for GutenTAG** to this folder.
- Download the index-file from below the table or [here](https://owncloud.hpi.de/s/3Cp8Q5H9gn7EVK0/download) and place it into the `<benchmark_data_path>`-folder. This file summarizes all "benchmark" datasets. As described on the web page, it misses the GutenTAG-datasets because they contain their own index-File (automatically generated).
- Create a folder for "GutenTAG" datasets: `mkdir <gutentag_data_path>`
- Extract the GutenTAG collection to `<gutentag_data_path>`

**Comment by CodeLionX** [comment] 2022-07-11 16:20
> Thanks again for your answers. it's okey for me. Now, how can I integrate the results of my algorithm into this notebook? do I just have to add the results (performance of my algorithm on each dataset) to the result file?

Yes 👍🏼

**Closed by CodeLionX** 2022-07-11 16:20 UTC
